import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Loader2,
  Menu,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  X,
} from "lucide-react";

export const Icons = {
  Close: X,
  Spinner: Loader2,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  Trash: Trash,
  Post: FileText,
  Page: File,
  Media: Image,
  Menu: Menu,
  Settings: Settings,
  Billing: CreditCard,
  More: MoreVertical,
  Add: Plus,
  Warning: AlertTriangle,
  User: User,
  ArrowRight: ArrowRight,
  Help: HelpCircle,
  Pizza: Pizza,
  Sun: SunMedium,
  Moon: Moon,
  Twitter: Twitter,
  Check: Check,
};
